---
- name: "Choose template source for {{ myservice }}-container-ansible.yaml"
  block:
    - set_fact:
        tht_template: "THT/new-myservice-container-ansible.yaml.j2"
      when: "{{ tht_input is not defined }}"
    - set_fact:
        tht_template: "THT/myservice-container-ansible.yaml.j2"
      when: "{{ tht_input is defined }}"

- name: Create {{ myservice }}-container-ansible.yaml template.
  template:
    src: "{{ tht_template }}"
    dest: "{{ tht_template_output_dir }}/{{ myservice }}-container-ansible.yaml"
