---
- set_fact:
    tht_template_output_dir: "{{output_dir}}/"
    myservice_titlecase: "{{ myservice|title }}"
    deploy_stages:
      - host_prep_tasks
      - external_deploy_tasks
      - deploy_steps_tasks
      - fast_forward_upgrade_tasks

- name: Create {{ myservice }}-container-ansible.yaml template.
  template:
    src: THT/myservice-container-ansible.yaml.j2
    dest: "{{ tht_template_output_dir }}/{{ myservice }}-container-ansible.yaml"
